# Site settings
title: cmdd.github.io
email: cmdd@airmail.cc
description: > # this means to ignore newlines until "baseurl:"
  Todo;
  Mirror of svbtle
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cmdd.github.io" # the base hostname & protocol for your site
twitter_username: cmdd_
github_username:  cmdd

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman